name: Deploy with Ngrok

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          # If you actually need more (numpy, pandas, tensorflow), add them here,
          # like in your doc:
          # pip install numpy pandas tensorflow

      - name: Install ngrok and jq
        run: |
          npm install -g ngrok
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Start app in background
        run: |
          python app.py &
          # wait until the app is healthy
          for i in {1..15}; do
            if curl -fsS http://127.0.0.1:5000/health >/dev/null; then
              echo "App is up"
              break
            fi
            sleep 1
          done

      - name: Start ngrok tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok authtoken "$NGROK_AUTH_TOKEN"
          ngrok http 5000 > ngrok.log &
          # wait for the tunnel to appear
          for i in {1..15}; do
            URL=$(curl -fsS http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[]?.public_url' | head -n1)
            if [ -n "$URL" ] && [ "$URL" != "null" ]; then
              echo "PUBLIC_URL=$URL" >> $GITHUB_ENV
              echo "Ngrok URL: $URL"
              break
            fi
            sleep 1
          done

      - name: Show URL in Job Summary
        run: |
          echo "### Ngrok Public URL" >> $GITHUB_STEP_SUMMARY
          echo "$PUBLIC_URL" >> $GITHUB_STEP_SUMMARY

      - name: Keep alive (10 minutes)
        run: sleep 10m
